### ISSUE TITLE
Update YML file to include digital ocean services

### ISSUE THREAD

**Issue by mbcse** [leopardslab/nodecloud#95]
### Describe the solution you'd like

- Update the Nodecloud yml file to include digital ocean services

### Impact

- NodeCloud code generation tool

**Comment by rajitha1998** [comment]
Before updating the YML file, its better to find out all the services can be generated with the parser and the transformer you are going to implement @mbcse. Because of this issue we had to create two transformers and parsers for Google Cloud. Please look into that whether there is a requirement as such.

**Comment by mbcse** [comment]
@rajitha1998 Okay sure will take care of this thing
